name: deployment-on-wabli-server
'on':
  repository_dispatch:
    types:
      - deploy
jobs:
  Deploy-the-code:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WABLI_SERVER_SSH_HOST }}
          username: ${{ secrets.WABLI_SERVER_SSH_USERNAME }}
          password: ${{ secrets.WABLI_SERVER_SSH_PASSWORD }}
          port: ${{ secrets.WABLI_SERVER_SSH_PORT }}
          script: >-
            ./wabli-applications/deploy.sh -b main -d wabli-contest-42206 -r
            https://github.com/wabliplatform/62a4e9f9db244ef1dea734d6-server-EasyParking.git
            -f 62a4e9f9db244ef1dea734d6-server-EasyParking -p 3044
